### ISSUE TITLE
raise KeyError(key) from None KeyError: 'config_file'

### ISSUE THREAD

**Issue by tcexeexe** [heartexlabs/label-studio-ml-backend#104]
Hello~
l try to run the object-detector example,and l follow the instruction of 
`https://github.com/heartexlabs/label-studio/blob/master/docs/source/tutorials/object-detector.md`
and download the checkpoint_file from MMDetection model zoo.
l use the order to start the service
`label-studio-ml init coco-detector --from label_studio_ml/examples/mmdetection/mmdetection.py`
`label-studio-ml start coco-detector --with config_file=./mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoint_file=/home/tcexeexe/dataDisk2/abel-studio-ml-backend/mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth`

My label setting is as follow
<img width="394" alt="1650125205(1)" src="https://user-images.githubusercontent.com/28287196/163682593-e1c9df8a-c254-4768-9453-3533bacc436f.png">
but there is still an error occourred when l try to connect the label-studio-ml-backend
<img width="521" alt="1650125340(1)" src="https://user-images.githubusercontent.com/28287196/163682646-8b850605-3230-43ae-b6c8-6d9a696c0528.png">

the error log from the backend is as follows:

```
[2022-04-17 00:29:16,909] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/api.py", line 50, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/model.py", line 502, in fetch
    model = cls.model_class(label_config=label_config, **kwargs)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/coco-detector/mmdetection.py", line 41, in __init__
    config_file = config_file or os.environ['config_file']
  File "/home/tcexeexe/anaconda3/envs/label_studio/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'config_file'

Traceback (most recent call last):
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/api.py", line 50, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/label_studio_ml/model.py", line 502, in fetch
    model = cls.model_class(label_config=label_config, **kwargs)
  File "/home/tcexeexe/dataDisk2/label-studio-ml-backend/coco-detector/mmdetection.py", line 41, in __init__
    config_file = config_file or os.environ['config_file']
  File "/home/tcexeexe/anaconda3/envs/label_studio/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'config_file'

[2022-04-17 00:29:16,909] [INFO] [werkzeug::_log::225] 10.168.1.217 - - [17/Apr/2022 00:29:16] "POST /setup HTTP/1.1" 500 -
```
where the problem might be?

**Comment by makseq** [comment]
Try this: 
```
config_file=/path/to/config/faster_rcnn_r50_fpn_1x.py label-studio-ml init coco-detector
config_file=/path/to/config/faster_rcnn_r50_fpn_1x.py label-studio-ml start coco-detector
```

**Comment by makseq** [comment]
Close as unanswered or solved issue.
