### ISSUE TITLE
Docker Compose: No module named '_wsgi'

### ISSUE THREAD

**Issue by jike212** [heartexlabs/label-studio-ml-backend#106]
When cloning the repo and running `docker-compose up` I receive the following:

```
Starting redis ... done
Starting server ... done
Attaching to redis, server
redis     | 1:C 22 Apr 2022 05:32:50.317 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 22 Apr 2022 05:32:50.317 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 22 Apr 2022 05:32:50.317 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis     | 1:M 22 Apr 2022 05:32:50.317 * monotonic clock: POSIX clock_gettime
redis     | 1:M 22 Apr 2022 05:32:50.318 * Running mode=standalone, port=6379.
redis     | 1:M 22 Apr 2022 05:32:50.318 # Server initialized
redis     | 1:M 22 Apr 2022 05:32:50.318 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis     | 1:M 22 Apr 2022 05:32:50.318 * Loading RDB produced by version 6.2.6
redis     | 1:M 22 Apr 2022 05:32:50.318 * RDB age 2 seconds
redis     | 1:M 22 Apr 2022 05:32:50.318 * RDB memory usage when created 0.77 Mb
redis     | 1:M 22 Apr 2022 05:32:50.318 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis     | 1:M 22 Apr 2022 05:32:50.318 * DB loaded from disk: 0.000 seconds
redis     | 1:M 22 Apr 2022 05:32:50.318 * Ready to accept connections
server    | Traceback (most recent call last):
server    |   File "/usr/local/bin/gunicorn", line 8, in <module>
server    |     sys.exit(run())
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
server    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
server    |     super().run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
server    |     Arbiter(self).run()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
server    |     self.setup(app)
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
server    |     self.app.wsgi()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
server    |     self.callable = self.load()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
server    |     return self.load_wsgiapp()
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
server    |     return util.import_app(self.app_uri)
server    |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
server    |     mod = importlib.import_module(module)
server    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
server    |     return _bootstrap._gcd_import(name[level:], package, level)
server    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server    |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
server    | ModuleNotFoundError: No module named '_wsgi'
server exited with code 1
```

**Comment by makseq** [comment]
@jike212 Could you write more details - what ML model do you run? What previous steps did you do?

**Comment by KonstantinKorotaev** [comment]
@jike212 to fix this issue just add uwsgi==2.0.19.1 to requirements file.
It seems that you are using old example, we are moving to using gunicorn.
What example do you use?

**Comment by jike212** [comment]
I believe I was using BERT. I wasn't able to replicate the exact same error again so I'll close this issue for the time being and re-open again if it comes up again. I'll also check into the newer examples when I get a chance to try it again. Thank you both!

**Comment by EuphoriaCelestial** [comment]
> @jike212 to fix this issue just add uwsgi==2.0.19.1 to requirements file. It seems that you are using old example, we are moving to using gunicorn. What example do you use?

I have added uwsgi to requirement file but it doesnt work. I even tried to install uwsgi manually
