### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

### ISSUE THREAD

**Issue by ealpha** [heartexlabs/label-studio-ml-backend#116]
Load new model from:  /label-studio-ml-backend/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py /label-studio-ml-backend/mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
[2022-05-22 04:13:15,529] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):

Traceback (most recent call last):
  File "label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "label_studio_ml/api.py", line 50, in _setup
    model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
  File "label_studio_ml/model.py", line 502, in fetch
    model = cls.model_class(label_config=label_config, **kwargs)
  File "coco-detector/mmdetection.py", line 68, in __init__
    self.model = init_detector(config_file, checkpoint_file, device=device)
  File "/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 363, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

**Comment by KonstantinKorotaev** [comment]
Hi @ealpha 
Do you use this model localy or in docker?
Could you please write your packages versions (ml backend, mmdet, etc)?

**Comment by vishal-ranjan** [comment]
i tried with the same configuration for object detection and got a similar error. it is some issue with mmdet and mmcv.

**Comment by KonstantinKorotaev** [comment]
> i tried with the same configuration for object detection and got a similar error. it is some issue with mmdet and mmcv.

Do you run it locally or in docker?

**Comment by makseq** [comment]
Closed as unanswered issue.
