### ISSUE TITLE
get_local_path doesn't work for local-files connector

### ISSUE THREAD

**Issue by d4l3k** [heartexlabs/label-studio-ml-backend#136]
I'm importing image files using the local files source and the image URLs are in the format

```
/data/local-files/?d=foo/bar.jpg
```
When calling `self.get_local_path` in LabelStudioMLBase derived class it just throws the error:

```
[2022-07-01 21:34:13,520] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/rice/venvs/-/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/rice/venvs/-/lib/python3.10/site-packages/label_studio_ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/rice/venvs/-/lib/python3.10/site-packages/label_studio_ml/model.py", line 582, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/mnt/ext/-/dense/labelstudio-dense/labelstudio.py", line 58, in predict
    image = self.get_local_path(task['data']['image'])
  File "/home/rice/venvs/-/lib/python3.10/site-packages/label_studio_ml/model.py", line 322, in get_local_path
    return get_local_path(url, project_dir=project_dir, hostname=self.hostname, access_token=self.access_token)
  File "/home/rice/venvs/-/lib/python3.10/site-packages/label_studio_tools/core/utils/io.py", line 59, in get_local_path
    raise FileNotFoundError(filepath)
FileNotFoundError: foo/bar.jpg/local-files/
```

**Comment by skanelo** [comment]
Hello!

I'm facing the exact same issue.

From the backend's side I get this message:
```
FileNotFoundError: Can't resolve url, neither hostname or project_dir passed: /data/upload/2/b9793581-Traigo80_li-ion20charging.jpgwidth768nameTraigo80_li-ion20charging.jpg

[2022-07-05 13:39:45,666] [INFO] [werkzeug::_log::225] 192.168.50.185 - - [05/Jul/2022 13:39:45] "POST /predict HTTP/1.1" 500 -
192.168.50.185 - - [05/Jul/2022 13:39:45] "POST /predict HTTP/1.1" 500 -
```

From the UI's side I get this message:
```
[2022-07-05 11:39:39,916] [ml.models::predict_tasks::171] [WARNING] Prediction not created for project Forklift Backend (id=1, url=http://192.168.50.185:9090): 500 Server Error: INTERNAL SERVER ERROR for url: http://192.168.50.185:9090/predict
[05/Jul/2022 11:39:39] "GET /api/tasks?page=1&page_size=30&view=5&project=2 HTTP/1.1" 200 7067
[05/Jul/2022 11:39:40] "GET /data/upload/2/b9793581-Traigo80_li-ion20charging.jpgwidth768nameTraigo80_li-ion20charging.jpg HTTP/1.1" 200 62374
[05/Jul/2022 11:39:44] "GET /api/label_links?project=2&expand=label HTTP/1.1" 200 52
[2022-07-05 11:39:45,667] [ml.models::predict_tasks::171] [WARNING] Prediction not created for project Forklift Backend (id=1, url=http://192.168.50.185:9090): 500 Server Error: INTERNAL SERVER ERROR for url: http://192.168.50.185:9090/predict
[05/Jul/2022 11:39:45] "GET /api/tasks/14?project=2 HTTP/1.1" 200 689

```

In the beginning, I was thinking that this issue comes from the fact that I have uploaded some sample images from my local device by just drag & drop. So I found on google images an image with an object of my interest and I imported this image by using its URL. The abovementioned messages come from the latter method I used to import my image.

(Everything else seems to be working properly, the only problem I'm having is that I cannot see the predictions of the model I've been using that are supposed to assist me to annotate new unlabeled images)

Any idea on how to resolve this?! 🥺

**Comment by KonstantinKorotaev** [comment]
@d4l3k 
It seems that there is some mistake in data urls:

> FileNotFoundError: foo/bar.jpg/**local-files/**

Could you please what goes into get_local_path method?

**Comment by d4l3k** [comment]
I'm calling it with

`/data/local-files/?d=foo/bar.jpg`

Which is from the `task['data']['image'[` field I believe

I've worked around it by parsing the image and joining it with the hard coded path on disk but that's less than ideal

**Comment by d4l3k** [comment]
Here's my code:

```
def predict(self, tasks, **kwargs):
        assert len(tasks) == 1

        print(tasks)
        predictions = []
        for task in tasks:
            image = task["data"]["image"]
            _, _, image = image.partition("?d=")
            image = os.path.join("../datasets", image)

            img = Image.open(image)
```

Ideally I want to be able to call `get_local_path(task["data"]["image"])` but that throws the error in the original post above

**Comment by KonstantinKorotaev** [comment]
1. What version of label studio tools do you use? 
2. Do you have such file **/data/foo/bar.jpg** locally in your file system in ml backend service?

**Comment by d4l3k** [comment]
versions
```
$ pip list | grep label-studio
label-studio                   1.5.0
label-studio-converter         0.0.40
label-studio-ml                1.0.8
label-studio-tools             0.0.0.dev11
```

Label studio connector:

![2022-07-05-103108_499x360_scrot](https://user-images.githubusercontent.com/909104/177384146-08d8aa7e-0028-42b4-8954-a9dad36071dc.png)

Example task:
```
{
  "id": 176992,
  "data": {
    "image": "/data/local-files/?d=imagespace/capture_main_20.jpg"
  }
}
```

**Comment by d4l3k** [comment]
On `label-studio-tools==0.0.0.dev14` it prints:

```
Traceback (most recent call last):
  File "/home/rice/venvs/openape/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/rice/venvs/openape/lib/python3.10/site-packages/label_studio_ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/rice/venvs/openape/lib/python3.10/site-packages/label_studio_ml/model.py", line 582, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/mnt/ext/openape/dense/labelstudio-dense/labelstudio.py", line 64, in predict
    path = self.get_local_path(task['data']['image'])
  File "/home/rice/venvs/openape/lib/python3.10/site-packages/label_studio_ml/model.py", line 322, in get_local_path
    return get_local_path(url, project_dir=project_dir, hostname=self.hostname, access_token=self.access_token)
  File "/home/rice/venvs/openape/lib/python3.10/site-packages/label_studio_tools/core/utils/io.py", line 61, in get_local_path
    raise FileNotFoundError(filepath)
FileNotFoundError: local-files/imagespace/capture_narrow_20.jpg
```

**Comment by KonstantinKorotaev** [comment]
@pinecho did you provide access_token  to your instance of label studio?

**Comment by KonstantinKorotaev** [comment]
@pinecho 
You should add it in __init__ of your model:
`self.access_token = access_token`

**Comment by pinecho** [comment]
@KonstantinKorotaev 
It works, thank you so much!

**Comment by KonstantinKorotaev** [comment]
@d4l3k 
Could you please update your label-studio-tools from [branch fb-DEV-2827](https://github.com/heartexlabs/label-studio-tools/tree/fb-DEV-2827) and try again?

**Comment by d4l3k** [comment]
Yup, that's working now. Thanks for the fix!
