### ISSUE TITLE
FileNotFoundError: Can't resolve url, neither hostname or project_dir passed

### ISSUE THREAD

**Issue by NL647** [heartexlabs/label-studio-ml-backend#143]
Hello, 
I set up the label studio via python (conda) on windows 10.
I try to add label studio ml backend (using docker) , using the example mmdetection.
I added it properly in UI, the server is started.
But I get an error that i don t know how to solve.
Can someone please help me to solve it?
My image are actually in this folder:  `C:\Users\user1\AppData\Local\label-studio\label-studio\media`

`FileNotFoundError: Can't resolve url, neither hostname or project_dir passed: /data/upload/3/`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 584, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "./mmdetection.py", line 92, in predict
    image_path = self.get_local_path(image_url)
  File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 322, in get_local_path
    return get_local_path(url, project_dir=project_dir, hostname=self.hostname, access_token=self.access_token)
  File "/usr/local/lib/python3.7/site-packages/label_studio_tools/core/utils/io.py", line 76, in get_local_path
    raise FileNotFoundError("Can't resolve url, neither hostname or project_dir passed: " + url)
FileNotFoundError: Can't resolve url, neither hostname or project_dir passed: /data/upload/3/698f8072-battery3.jpg`

Thank s in advance for your help.

**Comment by KonstantinKorotaev** [comment]
Hi @NL647 
Do you have such files in your docker container with ML backend?

**Comment by RayAdas-GA-17** [comment]
Hi @KonstantinKorotaev 
I run it in windows 10. But now, I make it work by update the label-studio. In the new version, it gets the image path with the environment variable “LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT”.
Thank you for your reply.

**Comment by raash1d** [comment]
@KonstantinKorotaev I am using the ML backend inside docker but my label-studio is running from a conda environment. Do you have a workaround for such an issue?

**Comment by makseq** [comment]
@raash1d the most efficient solution is to mount the local storage folder to docker and slightly change the file reading in the ML backend so that it reads files from the mounted folder.

**Comment by kaikaizhu** [comment]
主要愿意是project_dir后面不应该有‘upload’, get_local_path函数会在project_dir后面补一个upload
modify label_studio_ml/model.py as following:

def get_local_path(self, url, project_dir=None):
        return get_local_path(url, project_dir=project_dir.replace('/upload', '/'), hostname=self.hostname, access_token=self.access_token)
        #return get_local_path(url, project_dir=project_dir, hostname=self.hostname, access_token=self.access_token)
