### ISSUE TITLE
Error installing on Windows due to incorrect usage of uname()

### ISSUE THREAD

**Issue by csanadpoda** [heartexlabs/label-studio-ml-backend#232]
When installing on Windows machines, the command` pip install -r "...\label-studio-ml-backend\label_studio_ml\examples\tesseract\requirements.txt"` results in an error due to  `os.uname()` being called. On Windows systems, the correct command would be `platform.uname()`.

Stack trace:

  ```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Csanád\AppData\Local\Temp\pip-install-p77nn440\uwsgi_b4cbfe78a9d749e0966273c0acc5bef3\setup.py", line 3, in <module>
          import uwsgiconfig as uc
        File "C:\Users\Csanád\AppData\Local\Temp\pip-install-p77nn440\uwsgi_b4cbfe78a9d749e0966273c0acc5bef3\uwsgiconfig.py", line 8, in <module>
          uwsgi_os = os.uname()[0]
      AttributeError: module 'os' has no attribute 'uname'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by makseq** [comment]
I believe it's not label-studio-ml-backend problem, contact uwsgi developers please. 

Try to use docker compose to run it:
```
docker compose up
```
