### ISSUE TITLE
Error running containerized on Windows

### ISSUE THREAD

**Issue by csanadpoda** [heartexlabs/label-studio-ml-backend#234]
Steps to reproduce:
- Use Windows 11, up to date
- Install docker latest version
- Clone label-studio-ml-backend
- cd into default_configs
- run `docker compose up`

Following error appears:

```
[+] Running 2/0
 - Container redis   Created                                                                                       0.0s
 - Container server  Created                                                                                       0.0s
Attaching to redis, server
redis   | 1:C 28 Mar 2023 11:21:49.487 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis   | 1:C 28 Mar 2023 11:21:49.487 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
redis   | 1:C 28 Mar 2023 11:21:49.487 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis   | 1:M 28 Mar 2023 11:21:49.488 * monotonic clock: POSIX clock_gettime
redis   | 1:M 28 Mar 2023 11:21:49.488 * Running mode=standalone, port=6379.
redis   | 1:M 28 Mar 2023 11:21:49.488 # Server initialized
redis   | 1:M 28 Mar 2023 11:21:49.488 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis   | 1:M 28 Mar 2023 11:21:49.490 * Loading RDB produced by version 7.0.10
redis   | 1:M 28 Mar 2023 11:21:49.490 * RDB age 20 seconds
redis   | 1:M 28 Mar 2023 11:21:49.490 * RDB memory usage when created 0.82 Mb
redis   | 1:M 28 Mar 2023 11:21:49.490 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis   | 1:M 28 Mar 2023 11:21:49.491 * DB loaded from disk: 0.002 seconds
redis   | 1:M 28 Mar 2023 11:21:49.491 * Ready to accept connections
server  | Traceback (most recent call last):
server  |   File "/usr/local/bin/gunicorn", line 8, in <module>
server  |     sys.exit(run())
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
server  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
server  |     super().run()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
server  |     Arbiter(self).run()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
server  |     self.setup(app)
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
server  |     self.app.wsgi()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
server  |     self.callable = self.load()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
server  |     return self.load_wsgiapp()
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
server  |     return util.import_app(self.app_uri)
server  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
server  |     mod = importlib.import_module(module)
server  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
server  |     return _bootstrap._gcd_import(name[level:], package, level)
server  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
server  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
server  |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
server  | ModuleNotFoundError: No module named '_wsgi'
server exited with code 1
```
Looks like incorrect install for wsgi in docker image.

**Comment by makseq** [comment]
Please try to clone it again, I've added uwsgi dependency there.
