### ISSUE TITLE
API key with SAM

### ISSUE THREAD

**Issue by gebhaard** [heartexlabs/label-studio-ml-backend#285]
I deployed label-studio 1.8.0 in kubernetes, and deployed an ML Backend from the Segment Anything example.
I can connect to the ML Backend from the Label Studio, but I get the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/app/model.py", line 105, in predict
    image_path = get_image_local_path(img_path)
  File "/usr/local/lib/python3.8/site-packages/label_studio_ml/utils.py", line 46, in get_image_local_path
    return get_local_path(url, image_cache_dir, project_dir, get_env('HOSTNAME'), image_dir)
  File "/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py", line 84, in get_local_path
    raise FileNotFoundError("Can't access file, no access_token provided for Label Studio Backend")
FileNotFoundError: Can't access file, no access_token provided for Label Studio Backend`

I was trying to look at the example, but no idea how to specify the access token when deploying with docker/kubernetes.
Can anybody help me with this?

Thanks.

**Comment by jackmead515** [comment]
I solved this one... you can got to Account and Settings in the top right corner and retrieve the api key.

Then, with the ML backend, you can set the env variable: LABEL_STUDIO_ACCESS_TOKEN to that api key.

What Segment Anything ML backend version are you utilizing? I just cloned from master at commit: 8a1ff0348857657a94bd705f9e0fa12ffe6bca11
and I can't get it to work regardless.

**Comment by jackmead515** [comment]
https://github.com/heartexlabs/label-studio-tools/blob/62e3dc1cbda8100aef51d77056592927496f9af3/label_studio_tools/core/utils/io.py#L36C5-L36C19

https://github.com/heartexlabs/label-studio-ml-backend/blob/8a1ff0348857657a94bd705f9e0fa12ffe6bca11/label_studio_ml/utils.py#L45C3-L45C3

Looking at the line where the error is being through. The access_token isn't even past in! So this looks like a bug to me.
