### ISSUE TITLE
Missing config.json on SAM

### ISSUE THREAD

**Issue by RobinFrcd** [heartexlabs/label-studio-ml-backend#287]
Hi,
I'm trying to run the SAM backend provided in https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/segment_anything_model

I'm using the Docker version which builds fine, but when I try to run a prediction it fails with:

```
the kwargs are {'login': None, 'password': None, 'context': None}
the tasks are [{'id': 451102, 'data': {'image': 's3://....jpg', 'ref_id': 3602}, 'meta': {}, 'created_at': '2023-06-20T16:29:12.201416Z', 'updated_at': '2023-06-20T16:29:12.201442Z', 'is_labeled': False, 'overlap': 1, 'inner_id': 2, 'total_annotations': 0, 'cancelled_annotations': 0, 'total_predictions': 0, 'comment_count': 0, 'unresolved_comment_count': 0, 'last_comment_updated_at': None, 'project': 218, 'updated_by': None, 'file_upload': None, 'comment_authors': [], 'annotations': [], 'predictions': []}]
[2023-06-27 14:13:42,314] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
predictions = cls._current_model.model.predict(tasks, **kwargs)
File "/app/segment_anything_model.py", line 70, in predict
height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
predictions = cls._current_model.model.predict(tasks, **kwargs)
File "/app/segment_anything_model.py", line 70, in predict
height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable
```

Seems like kwargs are empty because of a missing config.json. How can I fix that ?

Thanks,
Robin

**Comment by jackmead515** [comment]
Bump same issue. This seems to be a persistent issue with label-studio 1.8.0

**Comment by sriramsk1999** [comment]
I'm facing the same issue with 1.7.3 as well, the context object in kwargs is None

**Comment by feicccccccc** [comment]
Encounter the same problem for label studio versions 1.6.0, 1.7.3, 1.8.0
It seems it's sever side (label studio) problem:
Request JSON:
```
{
 'tasks': [{'id': 128, 'data': {'image': '/data/local-files/?d=Documents/label_studio/dataset/coco128/000000000650.jpg'}, 'meta': {}, 'created_at': '2023-07-08T11:15:13.167604Z', 'updated_at': '2023-07-08T11:15:13.167616Z', 'is_labeled': False, 'overlap': 1, 'inner_id': 128, 'total_annotations': 0, 'cancelled_annotations': 0, 'total_predictions': 0, 'comment_count': 0, 'unresolved_comment_count': 0, 'last_comment_updated_at': None, 'project': 1, 'updated_by': None, 'file_upload': None, 'comment_authors': [], 'annotations': [], 'predictions': []}],
 'model_version': 'INITIAL',
 'project': '1.1688814855',
 'label_config': '<View>\n  <Image name="image" value="$image" zoom="true"/>\n  <BrushLabels name="tag" toName="image">\n  \t<Label value="Banana" background="#FF0000"/>\n  \t<Label value="Orange" background="#0d14d3"/>\n  </BrushLabels>\n  <KeyPointLabels name="tag2" toName="image">\n    <Label value="Banana" smart="true" background="#000000" showInline="true"/>\n    <Label value="Orange" smart="true" background="#000000" showInline="true"/>\n    <Label value="Orange Eraser" smart="true" background="#000000" showInline="true"/>\n  </KeyPointLabels>\n</View>', 
 'params': {'login': None, 'password': None, 'context': None}
}
```

**Comment by DaMuBo** [comment]
had the same issue.

Also tested it without docker. Getting the same error:


```
    height = kwargs['context']['result'][0]['original_height']
             ~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```


used label studio 1.7.1

**Comment by erinmikailstaples** [comment]
Hey all (@DaMuBo, @feicccccccc @sriramsk1999, @jackmead515, @RobinFrcd) 👋🏻 

We discussed this issue during our issue triage today and are flagging this for further inspection and review. 

Thank you all for your patience on this — I'll keep y'all posted on what we find.

[ see also https://github.com/heartexlabs/label-studio/issues/4493 ]

**Comment by DimIsaev** [comment]
I have the same problem!!

**Comment by hogepodge** [comment]
@shondle as the developer of the SAM feature, have you seen this issue in your own testing, and do you have a workaround?

**Comment by shondle** [comment]
Hi everyone, the video tutorial is included in the pull request above. Again, I have been able to replicate this without issue in varying environments, so please follow the video after the installation instructions to see if this works for you.

If it doesn't, please send a video in this issue showing your settings in the Machine Learning part of Label Studio, how you are getting a prediction with the tool in Label Studio, and the output in your ML backend terminal.

I realize this video won't address all issues, but I hope it helps a good amount of you.

**Comment by DaMuBo** [comment]
@shondle thanks a lot. I tried it with your fork and with the mobileSAM it works like a charm now.

Even without my GPU attached. So great work thanks 👍🏻

**Comment by botcs** [comment]
Hi all! 

Thanks @shondle for the great adaptation and @erinmikailstaples for maintaining the framework!
I think there's gonna be a lot more people discovering label-studio through SAM's adaptation, so I believe fixing this thread bug is really important.

At the moment I was trying to change a few things in the framework to get the ML backend started, but I believe there might be a version mismatch all over the examples?

The one that I bumped into first was the `init_app` signature in the `api.py` vs the ones in used in the `examples/*/_wsgi.py`  files.

Checking now #304 to see if that fixes the issue :) I'm sure I might be just missing something very basic stuff, let me know if I looked over something.

Thnks,
Csabi

**Comment by sriramsk1999** [comment]
I was also able to get it working without problems. Was most likely facing some environment issues. I reinstalled everything in a fresh env and it worked like a charm. Thanks for the nice work on this!

**Comment by Jerry2990** [comment]
i also has this problems. Is there any new solution?

**Comment by Jerry2990** [comment]
> @shondle thanks a lot. I tried it with your fork and with the mobileSAM it works like a charm now.
> 
> Even without my GPU attached. So great work thanks 👍🏻

did you run label-studio without **EMPTY CONTXTX**?

**Comment by DimIsaev** [comment]
no solution
