### ISSUE TITLE
Example simple_text_classifier.py Error

### ISSUE THREAD

**Issue by YigitBurdurlu** [heartexlabs/label-studio-ml-backend#56]
Hey, the new updates might have broken the initialization of example ml_backends. I follow the official steps to install;

git clone https://github.com/heartexlabs/label-studio-ml-backend
cd label-studio-ml-backend
pip install -U -e .
pip install -r label_studio_ml/examples/requirements.txt

label-studio-ml init  --script label_studio_ml/examples/simple_text_classifier.py

Traceback (most recent call last):                                                                                      
File "/data/workspace/tltenv/bin/label-studio-ml", line 33, in <module>                                               
    sys.exit(load_entry_point('label-studio-ml', 'console_scripts', 'label-studio-ml')())                               
File "/data/workspace/deep_cv/label-studio-ml-backend/label_studio_ml/server.py", line 119, in main                   
    create_dir(args)                                                                                                      
File "/data/workspace/deep_cv/label-studio-ml-backend/label_studio_ml/server.py", line 79, in create_dir              
    model_class = model_classes[0]                                                                                      
IndexError: list index out of range    

the commit : add00c8393220de4d9c5a12c38402119d6605d56 works fine

**Comment by venergiac-bh** [comment]
same problem here 

`get_all_classes_inherited_LabelStudioMLBase`

was not able to fin the right class

`label-studio-ml init my_ml_backend --script /label-studio-ml-backend/label_studio_ml/examples/simple_text_classifier.py`

returned 

`/label-studio-ml-backend/label_studio_ml/examples/simple_text_classifier.py
simple_text_classifier imported <module 'simple_text_classifier' (namespace)>
Traceback (most recent call last):
  File "/usr/local/bin/label-studio-ml", line 33, in <module>
    sys.exit(load_entry_point('label-studio-ml', 'console_scripts', 'label-studio-ml')())
  File "/label-studio-ml-backend/label_studio_ml/server.py", line 120, in main
    create_dir(args)
  File "/label-studio-ml-backend/label_studio_ml/server.py", line 80, in create_dir
    model_class = model_classes[0]
IndexError: list index out of range`

**Comment by venergiac-bh** [comment]
ops solved with

label-studio-ml init my_ml_backend --script /label-studio-ml-backend/label_studio_ml/examples/**simple_text_classifier/simple_text_classifier.py**

**Comment by makseq** [comment]
Recently we added separated folders for each example, your solutions is correct.

**Comment by wolfog** [comment]
@venergiac-bh thanks very much. the stem of simple_text_classifier.py must be same as name of it's parent directory.
